# Generated by Django 3.1.2 on 2023-10-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20231011_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={},
        ),
    ]
